#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 02, 2019 12:49:04 AM +0300  platform: Windows NT

import sys
users = None

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import add_user_gui_support

def vp_start_gui(userspass):
    """Starting point when module is the main routine."""
    global val, w, root, users
    root = tk.Tk()
    root.resizable(False, False)
    root.protocol("WM_DELETE_WINDOW", add_user_gui_support.destroy_window)
    users = userspass
    add_user_gui_support.set_Tk_var()
    top = Toplevel1(root)
    add_user_gui_support.init(root, top)
    root.mainloop()
    print add_user_gui_support.index
    print users[add_user_gui_support.index]
    if add_user_gui_support.index is not None:
        return users[add_user_gui_support.index]
    return None

w = None
def create_Toplevel1(root, *args, **kwargs):
    """Starting point when module is imported by another program."""
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    add_user_gui_support.set_Tk_var()
    top = Toplevel1 (w)
    add_user_gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w

    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        """This class configures and populates the toplevel window.
           top is the toplevel containing window."""
        global users
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {Segoe UI} -size 9"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("300x71+650+150")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(takefocus="1")

        self.Label = tk.Label(top)
        self.Label.place(relx=0.0, rely=-0.141, height=36, width=270)
        self.Label.configure(background="#d9d9d9")
        self.Label.configure(disabledforeground="#a3a3a3")
        self.Label.configure(font="-family {Segoe UI} -size 11")
        self.Label.configure(foreground="#000000")
        self.Label.configure(text="""Please choose the user you want to add:""")
        self.Label.configure(width=270)

        self.users_list = ttk.Combobox(top)
        self.users_list.place(relx=0.01, rely=0.211, relheight=0.296
                , relwidth=0.974)
        self.users_list.configure(textvariable=add_user_gui_support.combobox)
        self.users_list.configure(width=263)
        self.users_list.configure(values=users)
        self.users_list.bind("<FocusIn>", add_user_gui_support.defocus)
        self.users_list.config(state='readonly')

        self.done_button = tk.Button(top)
        self.done_button.place(relx=0.789, rely=0.563, height=24, width=57)
        self.done_button.configure(activebackground="#ececec")
        self.done_button.configure(activeforeground="#000000")
        self.done_button.configure(background="#d9d9d9")
        self.done_button.configure(command=add_user_gui_support.finished)
        self.done_button.configure(disabledforeground="#a3a3a3")
        self.done_button.configure(foreground="#000000")
        self.done_button.configure(highlightbackground="#d9d9d9")
        self.done_button.configure(highlightcolor="black")
        self.done_button.configure(pady="0")
        self.done_button.configure(text="""Done""")
        self.done_button.configure(width=57)

if __name__ == '__main__':
    vp_start_gui(['dan', 'ererz', 'yosi'])
