#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  Apr 13, 2019 02:47:19 AM +0300  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 600x450+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font "TkDefaultFont"
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo48 \
        -width 594 -height 446 -takefocus {} 
    vTcl:DefineAlias "$top.tNo48" "TNotebook1" vTcl:WidgetProc "Toplevel" 1
    frame $top.tNo48.t0 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t0" "TNotebook1_t0" vTcl:WidgetProc "Toplevel" 1
    $top.tNo48 add $top.tNo48.t0 \
        -padding 0 -sticky nsew -state normal -text {Page 1} -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo48.t0
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_0.scr52 \
        -background {#d9d9d9} -height 341 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 461 
    vTcl:DefineAlias "$site_4_0.scr52" "Scrolledtext1" vTcl:WidgetProc "Toplevel" 1

    $site_4_0.scr52.01 configure -background white \
        -font font9 \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_0.scr53 \
        -background {#d9d9d9} -height 61 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 431 
    vTcl:DefineAlias "$site_4_0.scr53" "Scrolledtext2" vTcl:WidgetProc "Toplevel" 1

    $site_4_0.scr53.01 configure -background white \
        -font font9 \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    button $site_4_0.but54 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command send_message \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Send Message} 
    vTcl:DefineAlias "$site_4_0.but54" "send" vTcl:WidgetProc "Toplevel" 1
    button $site_4_0.but59 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command view_users \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {View Users} 
    vTcl:DefineAlias "$site_4_0.but59" "view" vTcl:WidgetProc "Toplevel" 1
    button $site_4_0.but60 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command mute_unmute \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Mute/Umute Users} 
    vTcl:DefineAlias "$site_4_0.but60" "mute" vTcl:WidgetProc "Toplevel" 1
    button $site_4_0.but64 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command add_user -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Add User} 
    vTcl:DefineAlias "$site_4_0.but64" "add" vTcl:WidgetProc "Toplevel" 1
    button $site_4_0.but65 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command kick_user \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Kick User} 
    vTcl:DefineAlias "$site_4_0.but65" "kick" vTcl:WidgetProc "Toplevel" 1
    button $site_4_0.but66 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command appoint_manager \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Appoint A Manager} 
    vTcl:DefineAlias "$site_4_0.but66" "appoint" vTcl:WidgetProc "Toplevel" 1
    button $site_4_0.but67 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command create -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Create New Room} 
    vTcl:DefineAlias "$site_4_0.but67" "create" vTcl:WidgetProc "Toplevel" 1
    button $site_4_0.but68 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command exit_room \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Exit Room} 
    vTcl:DefineAlias "$site_4_0.but68" "exitbutton" vTcl:WidgetProc "Toplevel" 1
    place $site_4_0.scr52 \
        -in $site_4_0 -x 0 -y 0 -width 461 -relwidth 0 -height 341 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.scr53 \
        -in $site_4_0 -x 0 -y 350 -width 431 -relwidth 0 -height 61 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but54 \
        -in $site_4_0 -x 440 -y 350 -width 147 -relwidth 0 -height 64 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but59 \
        -in $site_4_0 -x 470 -y 0 -width 117 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but60 \
        -in $site_4_0 -x 470 -y 50 -width 117 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but64 \
        -in $site_4_0 -x 470 -y 100 -width 117 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but65 \
        -in $site_4_0 -x 470 -y 150 -width 117 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but66 \
        -in $site_4_0 -x 470 -y 200 -width 117 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but67 \
        -in $site_4_0 -x 470 -y 250 -width 117 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but68 \
        -in $site_4_0 -x 470 -y 300 -width 117 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo48.t1 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t1" "TNotebook1_t1" vTcl:WidgetProc "Toplevel" 1
    $top.tNo48 add $top.tNo48.t1 \
        -padding 0 -sticky nsew -state normal -text {Page 2} -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo48.t1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo48 \
        -in $top -x 0 -y 0 -width 594 -relwidth 0 -height 446 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

